pool:
  vmImage: vs2017-win2016
  demands: azureps

steps:
- task: AzurePowerShell@1
  displayName: "Run pester"
  inputs:
    azureSubscription: pmarques-azure-connection
    ScriptType: InlineScript
   ConnectedServiceNameARM: : pmarques-azure-connection
    Inline: |
      Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
      Install-Module -Name Pester -Force -Verbose -Scope CurrentUser
      Import-Module Pester
      $Location = "$(Parameters.Location)"
      $SubscriptionId = (Get-AzContext).Subscription.id
       #$outputFile = ".\TEST-RESULTS.xml"
      #Invoke-Pester -OutputFile $outputFile -OutputFormat NUnitXml @{Path="./Tests";Parameters=@{SubscriptionId=$SubscriptionId;Location=$Location}  
    azurePowerShellVersion: LatestVersion

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testRunTitle: Test Results for Pester
    buildPlatform: Windows
    testRunner: NUnit
    testResultsFiles: ./TEST-RESULTS.xml
    failTaskOnFailedTests: true
