steps:

- task: PowerShell@1
  displayName: "Run pester"
  inputs:
    failOnStandardError: true
    scriptType: inlineScript
    inlineScript: |
      [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

      Write-Verbose -Verbose "Getting pipeline variables"
      $Location = "$(Parameters.Location)"

      Write-Verbose -Verbose "Installing modules"
      Install-Module -Name Pester -MaximumVersion 4.10.0 -AllowClobber -Force -Scope CurrentUser
      Install-Module Az.Accounts -MinimumVersion 2.2.5 -AllowClobber -Force -Scope CurrentUser
      Install-Module Az.Storage -MinimumVersion 3.3.0 -AllowClobber -Force -Scope CurrentUser
      Install-Module Az.Resources -MinimumVersion 3.2.1 -AllowClobber -Force -Scope CurrentUser
      Install-Module Az.ManagedServiceIdentity -MinimumVersion 0.7.3 -AllowClobber -Force -Scope CurrentUser

      Write-Verbose -Verbose "Importing modules"
      Import-Module Pester -RequiredVersion 4.10.0 
      Import-Module Az.Accounts
      Import-Module Az.Storage
      Import-Module Az.Resources
      Import-Module Az.ManagedServiceIdentity

      Write-Verbose -Verbose "Authenticating"
      Connect-AzAccount -Identity

      $SubscriptionId = (Get-AzContext).Subscription.id
      Write-Verbose -Verbose "Subscription-> $SubscriptionId"

      Set-Location "$(Build.Repository.LocalPath)"
      $outputFile = ".\TEST-RESULTS.xml"
      Invoke-Pester -OutputFile $outputFile -OutputFormat NUnitXml @{Path="./Tests";Parameters=@{SubscriptionId=$SubscriptionId;Location=$Location}}

      # Clean up .Azure folder
      Remove-Item C:\windows\ServiceProfiles\NetworkService\.Azure -Recurse -Force 

      # Checking results to fail build if necessary
      [xml]$result = Get-Content .\TEST-RESULTS.xml
      if ($result.'test-results'.'test-suite'.result -ieq "failure")
      {
          throw "Pester has finished with failed tests"
      }

- task: PublishTestResults@1
  displayName: Publish Test Results
  inputs:
    testRunTitle: Test Results for Pester
    buildPlatform: Windows
    testRunner: NUnit
    testResultsFiles: ./TEST-RESULTS.xml
    failTaskOnFailedTests: true
  condition: succeededOrFailed()

- task: PowerShell@1
  displayName: "Remove result file"
  inputs:
    failOnStandardError: true
    scriptType: inlineScript
    inlineScript: |
      $outputFile = ".\TEST-RESULTS.xml"
      Remove-Item $outputFile
