pool:
  vmImage: vs2017-win2016
  demands: azureps

steps:
- task: AzurePowerShell@1
  displayName: "Run pester"
  inputs:
    azureSubscription: pmarques-azure-connection
    ScriptType: InlineScript
    ConnectedServiceNameSelector: ConnectedServiceNameARM
    ConnectedServiceNameARM: pmarques-azure-connection
    Inline: |
      Install-Module -Name Pester -Force -Scope CurrentUser
      Install-Module Az -Force -Scope CurrentUser -AllowClobber
      Import-Module Pester
      $Location = "$(Parameters.Location)"
      $SubscriptionId = (Get-AzureRmContext).SubscriptionId
      write-host "Location: $Location"
      write-host "Subscription: $SubscriptionId"
      Set-Location "$(Build.Repository.LocalPath)"
      $outputFile = ".\TEST-RESULTS.xml"
      Invoke-Pester -OutputFile $outputFile -OutputFormat NUnitXml @{Path="./Tests";Parameters=@{SubscriptionId=$SubscriptionId;Location=$Location}}
    azurePowerShellVersion: LatestVersion

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testRunTitle: Test Results for Pester
    buildPlatform: Windows
    testRunner: NUnit
    testResultsFiles: ./TEST-RESULTS.xml
    failTaskOnFailedTests: true
